import type { Roadmap } from "./types";

/**
 * Roadmap → PDF, laid out like the reference document: a cover page carrying
 * the overview and prerequisites, then one page per phase.
 *
 * jsPDF is imported dynamically — it and its dependencies are ~500KB, and most
 * visitors never press Download.
 */
export async function buildRoadmapPdf(roadmap: Roadmap) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  const PAGE_W = doc.internal.pageSize.getWidth();
  const PAGE_H = doc.internal.pageSize.getHeight();
  const M = 48;
  const W = PAGE_W - M * 2;
  const BOTTOM = PAGE_H - 60;

  const INK = "#151515";
  const MUTED = "#6b6b6b";
  const ACCENT = "#c026a8";
  const DIFFICULTY: Record<string, string> = {
    Beginner: "#16a34a",
    Intermediate: "#ca8a04",
    Advanced: "#dc2626",
  };

  let y = M;
  let page = 1;

  const footer = () => {
    doc.setFont("helvetica", "normal").setFontSize(8).setTextColor(MUTED);
    doc.text(`Kareer Guide · Page ${page}`, M, PAGE_H - 32);
  };

  const newPage = () => {
    footer();
    doc.addPage();
    page += 1;
    y = M;
  };

  /** Write wrapped text, breaking to a new page when it would overflow. */
  const text = (
    value: string,
    opts: { size?: number; bold?: boolean; color?: string; gap?: number; indent?: number } = {},
  ) => {
    const { size = 10, bold = false, color = INK, gap = 4, indent = 0 } = opts;
    doc.setFont("helvetica", bold ? "bold" : "normal").setFontSize(size);
    doc.setTextColor(color);
    for (const line of doc.splitTextToSize(value, W - indent) as string[]) {
      if (y + size > BOTTOM) newPage();
      doc.text(line, M + indent, y);
      y += size + 2;
    }
    y += gap;
  };

  const heading = (label: string) => {
    if (y + 24 > BOTTOM) newPage();
    y += 6;
    doc.setFont("helvetica", "bold").setFontSize(9).setTextColor(MUTED);
    doc.text(label.toUpperCase(), M, y);
    y += 6;
    doc
      .setDrawColor(220)
      .setLineWidth(0.5)
      .line(M, y, M + W, y);
    y += 12;
  };

  /* ------------------------------ cover page ------------------------------ */

  doc.setFont("helvetica", "bold").setFontSize(9).setTextColor(ACCENT);
  doc.text("KAREER GUIDE", M, y);
  y += 20;

  text("Career Roadmap", { size: 12, color: MUTED, gap: 2 });
  text(roadmap.role, { size: 26, bold: true, gap: 14 });

  if (roadmap.overview) text(roadmap.overview, { size: 10.5, color: MUTED, gap: 12 });

  const meta = [
    roadmap.totalDuration && `Total Duration: ${roadmap.totalDuration}`,
    `${roadmap.phases.length} Phases`,
  ]
    .filter(Boolean)
    .join("  |  ");
  text(meta, { size: 10, bold: true, gap: 18 });

  if (roadmap.prerequisites.length) {
    heading("Prerequisites");
    for (const pre of roadmap.prerequisites) {
      text(`•  ${pre}`, { size: 10, color: MUTED, gap: 2 });
    }
  }

  doc.setFont("helvetica", "normal").setFontSize(8).setTextColor(MUTED);
  doc.text(`Generated by Kareer Guide on ${new Date().toLocaleDateString()}`, M, PAGE_H - 52);

  /* ------------------------------- phases -------------------------------- */

  roadmap.phases.forEach((p, i) => {
    newPage();

    // Phase header: title left, duration and difficulty right.
    doc.setFont("helvetica", "bold").setFontSize(14).setTextColor(INK);
    const title = `Phase ${i + 1}: ${p.phase}`;
    const titleLines = doc.splitTextToSize(title, W - 150) as string[];
    for (const line of titleLines) {
      doc.text(line, M, y);
      y += 16;
    }

    const metaTop = y - 16 * titleLines.length;
    doc.setFont("helvetica", "normal").setFontSize(9).setTextColor(MUTED);
    const durationText = p.duration;
    doc.text(durationText, M + W, metaTop, { align: "right" });
    doc.setFont("helvetica", "bold").setTextColor(DIFFICULTY[p.difficulty] ?? MUTED);
    doc.text(p.difficulty, M + W, metaTop + 12, { align: "right" });

    y += 6;
    if (p.description) text(p.description, { size: 10, color: MUTED, gap: 8 });

    if (p.topics.length) {
      heading("Topics & Skills");
      for (const t of p.topics) {
        text(`•  ${t.name}`, { size: 10, bold: true, gap: 1 });
        if (t.detail) text(t.detail, { size: 9.5, color: MUTED, indent: 14, gap: 6 });
      }
    }

    if (p.tools.length) {
      heading("Tools & Technologies");
      text(p.tools.join("   ·   "), { size: 10, color: MUTED, gap: 6 });
    }

    if (p.resources.length) {
      heading("Recommended Resources");
      for (const r of p.resources) {
        const line = `•  ${r.title}${r.author ? ` by ${r.author}` : ""}  [${r.type}]`;
        text(line, { size: 10, color: MUTED, gap: 2 });
      }
    }

    if (p.projects.length) {
      heading("Hands-on Projects");
      p.projects.forEach((proj, k) => {
        text(`${k + 1}.  ${proj}`, { size: 10, color: MUTED, gap: 4 });
      });
    }

    if (p.milestone) {
      if (y + 40 > BOTTOM) newPage();
      y += 8;
      doc.setFillColor(245, 245, 245);
      const boxTop = y - 10;
      const lines = doc.splitTextToSize(p.milestone, W - 24) as string[];
      const boxH = 26 + lines.length * 12;
      doc.rect(M, boxTop, W, boxH, "F");
      doc.setFillColor(ACCENT).rect(M, boxTop, 3, boxH, "F");

      doc.setFont("helvetica", "bold").setFontSize(8).setTextColor(MUTED);
      doc.text("MILESTONE", M + 12, y + 2);
      y += 14;
      doc.setFont("helvetica", "bold").setFontSize(10).setTextColor(INK);
      for (const line of lines) {
        doc.text(line, M + 12, y + 2);
        y += 12;
      }
      y += 12;
    }
  });

  footer();
  return doc;
}

/** Build the document and hand it to the browser as a download. */
export async function downloadRoadmapPdf(roadmap: Roadmap): Promise<void> {
  const doc = await buildRoadmapPdf(roadmap);
  doc.save(`KareerGuide_Roadmap_${roadmap.role.replace(/[^A-Za-z0-9]+/g, "_")}.pdf`);
}
