/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DreamJobRouteImport } from './routes/dream-job'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ResumeAnalysisRouteImport } from './routes/resume-analysis'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SavedJobsRouteImport } from './routes/saved-jobs'
import { Route as TailorResumeRouteImport } from './routes/tailor-resume'
import { Route as TailoredResumeRouteImport } from './routes/tailored-resume'
import { Route as DreamJobHistoryRouteImport } from './routes/dream-job_.history'
import { Route as DreamJobResultsRouteImport } from './routes/dream-job_.results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamJobRoute = DreamJobRouteImport.update({
  id: '/dream-job',
  path: '/dream-job',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeAnalysisRoute = ResumeAnalysisRouteImport.update({
  id: '/resume-analysis',
  path: '/resume-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedJobsRoute = SavedJobsRouteImport.update({
  id: '/saved-jobs',
  path: '/saved-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorResumeRoute = TailorResumeRouteImport.update({
  id: '/tailor-resume',
  path: '/tailor-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const TailoredResumeRoute = TailoredResumeRouteImport.update({
  id: '/tailored-resume',
  path: '/tailored-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamJobHistoryRoute = DreamJobHistoryRouteImport.update({
  id: '/dream-job_/history',
  path: '/dream-job/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamJobResultsRoute = DreamJobResultsRouteImport.update({
  id: '/dream-job_/results',
  path: '/dream-job/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dream-job': typeof DreamJobRoute
  '/jobs': typeof JobsRoute
  '/mcp': typeof McpRoute
  '/recommendations': typeof RecommendationsRoute
  '/resume-analysis': typeof ResumeAnalysisRoute
  '/roadmap': typeof RoadmapRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/tailor-resume': typeof TailorResumeRoute
  '/tailored-resume': typeof TailoredResumeRoute
  '/dream-job/history': typeof DreamJobHistoryRoute
  '/dream-job/results': typeof DreamJobResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dream-job': typeof DreamJobRoute
  '/jobs': typeof JobsRoute
  '/mcp': typeof McpRoute
  '/recommendations': typeof RecommendationsRoute
  '/resume-analysis': typeof ResumeAnalysisRoute
  '/roadmap': typeof RoadmapRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/tailor-resume': typeof TailorResumeRoute
  '/tailored-resume': typeof TailoredResumeRoute
  '/dream-job/history': typeof DreamJobHistoryRoute
  '/dream-job/results': typeof DreamJobResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dream-job': typeof DreamJobRoute
  '/jobs': typeof JobsRoute
  '/mcp': typeof McpRoute
  '/recommendations': typeof RecommendationsRoute
  '/resume-analysis': typeof ResumeAnalysisRoute
  '/roadmap': typeof RoadmapRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/tailor-resume': typeof TailorResumeRoute
  '/tailored-resume': typeof TailoredResumeRoute
  '/dream-job_/history': typeof DreamJobHistoryRoute
  '/dream-job_/results': typeof DreamJobResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dream-job'
    | '/jobs'
    | '/mcp'
    | '/recommendations'
    | '/resume-analysis'
    | '/roadmap'
    | '/saved-jobs'
    | '/tailor-resume'
    | '/tailored-resume'
    | '/dream-job/history'
    | '/dream-job/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dream-job'
    | '/jobs'
    | '/mcp'
    | '/recommendations'
    | '/resume-analysis'
    | '/roadmap'
    | '/saved-jobs'
    | '/tailor-resume'
    | '/tailored-resume'
    | '/dream-job/history'
    | '/dream-job/results'
  id:
    | '__root__'
    | '/'
    | '/dream-job'
    | '/jobs'
    | '/mcp'
    | '/recommendations'
    | '/resume-analysis'
    | '/roadmap'
    | '/saved-jobs'
    | '/tailor-resume'
    | '/tailored-resume'
    | '/dream-job_/history'
    | '/dream-job_/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DreamJobRoute: typeof DreamJobRoute
  JobsRoute: typeof JobsRoute
  McpRoute: typeof McpRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ResumeAnalysisRoute: typeof ResumeAnalysisRoute
  RoadmapRoute: typeof RoadmapRoute
  SavedJobsRoute: typeof SavedJobsRoute
  TailorResumeRoute: typeof TailorResumeRoute
  TailoredResumeRoute: typeof TailoredResumeRoute
  DreamJobHistoryRoute: typeof DreamJobHistoryRoute
  DreamJobResultsRoute: typeof DreamJobResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dream-job': {
      id: '/dream-job'
      path: '/dream-job'
      fullPath: '/dream-job'
      preLoaderRoute: typeof DreamJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-analysis': {
      id: '/resume-analysis'
      path: '/resume-analysis'
      fullPath: '/resume-analysis'
      preLoaderRoute: typeof ResumeAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-jobs': {
      id: '/saved-jobs'
      path: '/saved-jobs'
      fullPath: '/saved-jobs'
      preLoaderRoute: typeof SavedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailor-resume': {
      id: '/tailor-resume'
      path: '/tailor-resume'
      fullPath: '/tailor-resume'
      preLoaderRoute: typeof TailorResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailored-resume': {
      id: '/tailored-resume'
      path: '/tailored-resume'
      fullPath: '/tailored-resume'
      preLoaderRoute: typeof TailoredResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dream-job_/history': {
      id: '/dream-job_/history'
      path: '/dream-job/history'
      fullPath: '/dream-job/history'
      preLoaderRoute: typeof DreamJobHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dream-job_/results': {
      id: '/dream-job_/results'
      path: '/dream-job/results'
      fullPath: '/dream-job/results'
      preLoaderRoute: typeof DreamJobResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DreamJobRoute: DreamJobRoute,
  JobsRoute: JobsRoute,
  McpRoute: McpRoute,
  RecommendationsRoute: RecommendationsRoute,
  ResumeAnalysisRoute: ResumeAnalysisRoute,
  RoadmapRoute: RoadmapRoute,
  SavedJobsRoute: SavedJobsRoute,
  TailorResumeRoute: TailorResumeRoute,
  TailoredResumeRoute: TailoredResumeRoute,
  DreamJobHistoryRoute: DreamJobHistoryRoute,
  DreamJobResultsRoute: DreamJobResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
